# Generated by Django 4.2.3 on 2023-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazzy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
